# Generated by Django 4.1.3 on 2022-11-26 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='parents-photos/')),
                ('date_of_birth', models.DateField(null=True, verbose_name='تاريخ الميلاد')),
                ('place_of_birth', models.CharField(blank=True, max_length=45, null=True, verbose_name='مكان الميلاد')),
                ('blood_group', models.CharField(blank=True, choices=[('a+', 'A+'), ('o+', 'O+'), ('b+', 'B+'), ('ab+', 'AB+'), ('a-', 'A-'), ('o-', 'O-'), ('b-', 'B-'), ('ab-', 'AB-')], max_length=5, null=True, verbose_name='فصيلة الدم')),
                ('id_file', models.FileField(blank=True, upload_to='documents/', verbose_name='ملف الهوية الشخصية')),
                ('phone_no', models.CharField(blank=True, max_length=11, null=True, verbose_name='رقم المحمول')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents', to='address.location', verbose_name='محل السكن')),
            ],
        ),
    ]
