# Generated by Django 3.1.14 on 2022-11-22 02:29

from django.db import migrations, models
import django.db.models.deletion
import parent.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='parents-photos/')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Date of birth')),
                ('place_of_birth', models.CharField(blank=True, max_length=45, null=True, verbose_name='Place of birth')),
                ('gender', models.CharField(blank=True, max_length=50, null=True, verbose_name='student.Gender')),
                ('blood_group', models.CharField(blank=True, choices=[('a+', 'A+'), ('o+', 'O+'), ('b+', 'B+'), ('ab+', 'AB+'), ('a-', 'A-'), ('o-', 'O-'), ('b-', 'B-'), ('ab-', 'AB-')], max_length=5, null=True)),
                ('id_type', models.CharField(max_length=50, null=True, verbose_name=parent.models.IdType)),
                ('id_file', models.FileField(blank=True, upload_to='documents/')),
                ('phone_no', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents', to='address.location', verbose_name='place of live')),
            ],
        ),
    ]
