# Generated by Django 3.1.14 on 2022-11-22 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0002_auto_20221122_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='id_type',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parent.idtype'),
        ),
    ]
