# Generated by Django 3.1.14 on 2022-11-23 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20221123_2147'),
        ('parent', '0003_auto_20221122_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents', to='address.location', verbose_name='محل السكن'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='مكان الميلاد'),
        ),
    ]
