# Generated by Django 4.1.3 on 2022-11-26 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='المديرية')),
                ('dist_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='رمز المديرية')),
            ],
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True, unique=True, verbose_name='المحافظة')),
                ('gov_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رمز المحافظة')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='الملاحظات')),
            ],
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='العزلة')),
                ('sub_dist_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='رمز العزلة')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.district')),
                ('governorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.governorate')),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='القرية')),
                ('village_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='رمز القرية')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.district')),
                ('governorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.governorate')),
                ('sub_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.subdistrict')),
            ],
        ),
        migrations.CreateModel(
            name='SubVillage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='المحلة')),
                ('sub_village_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='رمز المحلة')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.district')),
                ('governorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.governorate')),
                ('sub_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.subdistrict')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.village')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='المعرف')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='الملاحظات')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.district')),
                ('governorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.governorate')),
                ('location_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.locationtype')),
                ('sub_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.subdistrict')),
                ('sub_village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.subvillage')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.village')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.governorate'),
        ),
    ]
