# Generated by Django 3.1.14 on 2022-11-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationtype',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='المديرية'),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='gov_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رمز المحافظة'),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='الملاحظات'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='المعرف'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='location',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='الملاحظات'),
        ),
        migrations.AlterField(
            model_name='subdistrict',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='العزلة'),
        ),
        migrations.AlterField(
            model_name='subdistrict',
            name='sub_dist_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رمز العزلة'),
        ),
        migrations.AlterField(
            model_name='subvillage',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='المحلة'),
        ),
        migrations.AlterField(
            model_name='subvillage',
            name='sub_village_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رمز المحلة'),
        ),
        migrations.AlterField(
            model_name='village',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='القرية'),
        ),
        migrations.AlterField(
            model_name='village',
            name='village_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رمز القرية'),
        ),
    ]
