# Generated by Django 3.1.14 on 2022-11-22 02:29

from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parent', '__first__'),
        ('address', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_certificate', models.FileField(blank=True, upload_to='documents/')),
                ('release_letter', models.FileField(blank=True, upload_to='documents/')),
                ('testimonial', models.FileField(blank=True, upload_to='documents/')),
                ('marksheet', models.FileField(blank=True, upload_to='documents/')),
                ('stipen_certificate', models.FileField(blank=True, upload_to='documents/')),
                ('other_certificate', models.FileField(blank=True, upload_to='documents/')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_code', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='school code')),
                ('name', models.CharField(blank=True, max_length=45, null=True, unique=True, verbose_name='school name')),
                ('phone_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='phone number')),
                ('school_gender', models.CharField(blank=True, max_length=50, null=True, verbose_name=student.models.SchoolGender)),
                ('shift', models.CharField(blank=True, max_length=50, null=True, verbose_name=student.models.Shift)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.location', verbose_name='address')),
            ],
            options={
                'verbose_name': 'school',
                'verbose_name_plural': 'schhols',
            },
        ),
        migrations.CreateModel(
            name='SchoolGender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SPNType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('emis_id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student-photos/')),
                ('blood_group', models.CharField(blank=True, choices=[('a+', 'A+'), ('o+', 'O+'), ('b+', 'B+'), ('ab+', 'AB+'), ('a-', 'A-'), ('o-', 'O-'), ('b-', 'B-'), ('ab-', 'AB-')], max_length=5, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True, verbose_name=student.models.Gender)),
                ('year', models.CharField(blank=True, max_length=10, null=True, verbose_name=student.models.Year)),
                ('shift', models.CharField(blank=True, max_length=50, null=True, verbose_name=student.models.Shift)),
                ('spn_type', models.CharField(blank=True, max_length=10, null=True, verbose_name=student.models.SPNType)),
                ('phone_no', models.CharField(blank=True, max_length=11, null=True, verbose_name='phone number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('father_job', models.CharField(blank=True, max_length=50, null=True, verbose_name='father jop')),
                ('father_monthly_income', models.IntegerField(blank=True, null=True, verbose_name='father monthly income')),
                ('relation', models.CharField(blank=True, max_length=50, null=True)),
                ('checked', models.BooleanField(default=False, verbose_name='checking')),
                ('added_date', models.DateField(auto_now_add=True, verbose_name='Add date ')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Note')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.location')),
                ('documents', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.document')),
                ('grade', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.grade')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parent.parent')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.school')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.AddField(
            model_name='school',
            name='levels',
            field=models.ManyToManyField(related_name='school', to='student.SchoolLevel'),
        ),
    ]
