# Generated by Django 3.1.14 on 2022-11-22 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'school', 'verbose_name_plural': 'schools'},
        ),
        migrations.AlterField(
            model_name='school',
            name='school_gender',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.schoolgender'),
        ),
        migrations.AlterField(
            model_name='school',
            name='shift',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.shift'),
        ),
    ]
