# Generated by Django 3.1.14 on 2022-11-23 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20221123_2147'),
        ('student', '0002_auto_20221122_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'وثيقة', 'verbose_name_plural': 'الوثائق'},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='relation',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'مدرسة', 'verbose_name_plural': 'المدارس'},
        ),
        migrations.AlterModelOptions(
            name='schoolgender',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='schoollevel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='spntype',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='studentinfo',
            options={'verbose_name': 'طالب', 'verbose_name_plural': 'الطلاب'},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.location', verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True, verbose_name='اسم المدرسة'),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم المحمول'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_code',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='رمز المدرسة'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='added_date',
            field=models.DateField(auto_now_add=True, verbose_name='أضف تاريخ '),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='تحقق'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='father_job',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='وظيفة الأب'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='father_monthly_income',
            field=models.IntegerField(blank=True, null=True, verbose_name='دخل الأب الشهري'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='gender',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.gender'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ملاحظة'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='phone_no',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='رقم المحمول'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='relation',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.relation'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='shift',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.shift'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='spn_type',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.spntype'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='year',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.year'),
        ),
    ]
